logging:
  # slf4j日志级别
  level: debug
spring:
  datasource:
    ########################### MySQL数据源配置 ##################
    # MySQL连接驱动
    driver-class-name: com.mysql.jdbc.Driver
    # MySQL地址
    url: jdbc:mysql://www.gotojava.cn:3306/spring-boot-jpa-demo?characterEncoding=utf-8&useSSL=false
    # MySQL连接用户名
    username: root
    # MySQL连接密码
    password: 
  jpa:
    # 查看运行时的SQL语句
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      # 通过实体生成表结构
      ddl-auto: update

  # 静态资源映射
  mvc:
    static-path-pattern: /static/**